# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '14.0'
prepare_react_native_project!

use_frameworks!

source 'https://cdn.cocoapods.org/' # Default global repository
source 'https://github.com/hotmic-wp/hotmic-media-player-cocoapod-specs.git'
source 'https://github.com/bitmovin/cocoapod-specs.git'

flipper_enabled = ENV['FLIPPER_ENABLED'] == "1"

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AwesomeProject' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,#flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Flipper configuration
    :flipper_configuration => flipper_enabled ? FlipperConfiguration.enabled : FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'HotMicMediaPlayer'

  target 'AwesomeProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end

      # Exclude Flipper libraries if Flipper is disabled
      unless flipper_enabled
        target.build_phases.each do |build_phase|
          if build_phase.display_name.start_with?("CopyPodsResources")
            target.build_phases.move(build_phase, to: 0)
          end
        end

        if target.name == 'FBReactNativeSpec'
          target.build_phases.each do |build_phase|
            if build_phase.display_name.start_with?("CopyPodsResources")
              target.build_phases.move(build_phase, to: 0)
            end
          end
        end
      end
    end
  end
end

